/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_javadecklink_Capture */

#ifndef _Included_us_ihmc_javadecklink_Capture
#define _Included_us_ihmc_javadecklink_Capture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     us_ihmc_javadecklink_Capture
 * Method:    getHardwareTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_javadecklink_Capture_getHardwareTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_javadecklink_Capture
 * Method:    startCaptureNative
 * Signature: (Ljava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_javadecklink_Capture_startCaptureNative
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     us_ihmc_javadecklink_Capture
 * Method:    stopCaptureNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_javadecklink_Capture_stopCaptureNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     us_ihmc_javadecklink_Capture
 * Method:    createCaptureSettings
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_javadecklink_Capture_createCaptureSettings
  (JNIEnv *, jobject, jint);

/*
 * Class:     us_ihmc_javadecklink_Capture
 * Method:    setQuality
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_us_ihmc_javadecklink_Capture_setQuality
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     us_ihmc_javadecklink_Capture
 * Method:    setOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_javadecklink_Capture_setOption
  (JNIEnv *, jobject, jlong, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
